name: Release

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release Tag'
        required: true
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.event.inputs.release }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Generate release artifacts
      id: generate
      run: |
        kustomize build . > strategies.yaml
        echo "file=strategies.yaml" >> "$GITHUB_OUTPUT"
    - name: Upload release artifacts
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ARTIFACT: ${{ steps.generate.outputs.file }}
      run: |
        gh release create ${TAG} --draft --generate-notes
        gh release upload ${TAG} "${ARTIFACT}"
